Admin_module/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ProjectHomePage, name='ProjectHomePage'),
    path('EventManagerHomePage', views.EventManagerHomePage, name='EventManagerHomePage'),
    path('EventParticipantHomePage', views.EventParticipantHomePage, name='EventParticipantHomePage'),
    path('signup', views.Signup, name='signup'),
    path('signup1',views.signup1,name='signup1'),
    path('login', views.login, name='login'),
    path('login1', views.login1, name='login1'),
    path('logout', views.logout, name='logout'),
    path('account_details', views.account_details, name='account_details'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('AboutUs', views.AboutUs, name='AboutUs'),
    path('OurServices', views.OurServices, name='OurServices'),
    path('ContactUs', views.ContactUs, name='ContactUs'),
    path('Gallery', views.Gallery, name='Gallery'),

]

EventManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Admin_module.urls')),
    path('EventManager/',include('EventManager_module.urls')),
    path('EventParticipant/',include('EventParticipant_module.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

EventManager_module/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import accept_application
from .views import reject_application



app_name = 'EventManager_module'
urlpatterns = [
    path('eventpost/',views.Eventpost,name='Event Post'),
    path('add_event_details', views.add_event_details,name='add_event_details'),
    path('view/',views.view_event_details,name='view_event_details'),
    path('edit/<int:event_id>',views.edit_event_details,name='edit_event_details'),
    path('delete/<int:event_id>/', views.delete_event_details, name='delete_event_details'),
    path('event_application_list/',views.event_application_list, name = 'event_application_list'),
    path('KLU/', views.KLU, name='EventPostklu'),
    path('KLH/', views.KLH, name='EventPostklh'),
    path('vitap/',views.vitap,name = 'EventPostvitap'),
    path('vitchennai/', views.vitchennai, name='EventPostvitchennai'),
    path('srm/', views.srm, name='EventPostsrm'),
    path('gitam/', views.gitam, name='EventPostgitam'),
    path('gmrit/', views.gmrit, name='EventPostgmrit'),
    path('AU/', views.AU, name='EventPostau'),
    path('accept_application/<int:event_application_id>/', views.accept_application, name='accept_application'),
    path('reject_application/<int:event_application_id>/', reject_application, name='reject_application'),

]

EventParticipant_module/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'EventParticipant_module'
urlpatterns = [
path('viewevents', views.viewEvents, name='View Events'),
path('event_details_list',views.event_details_list,name = "event_details_list"),
path('submit_form/',views.submit_form,name = 'submit_form'),
path('add_eventparticipant_profile/',views.add_eventparticipant_profile,name = 'add_eventparticipant_profile'),
path('apply/<int:event_id>/',views.register_to_event,name ='register_to_event'),


]

templates/Navbar/EventManagerNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<style>
    /* Dropdown Styles */
        .profile-dropdown {
            position: relative;
            display: inline-block;
        }

        .profile-image {
            width: 40px; /* Adjust as needed */
            height: 40px; /* Adjust as needed */
            border-radius: 50%; /* To make it circular */
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 120px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
            top: 100%; /* Position the dropdown below the profile image */
            right: 0; /* Align the dropdown to the right edge of the profile image */
            animation: fadeIn 0.5s ease;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .profile-dropdown:hover .dropdown-content {
            display: block;
         }
    /* footer section start */
</style>
<nav class="navbar navbar-expand-lg " style ="background-color: black">
  <div class="container-fluid">
    <a class="navbar-brand" style="font-weight: bold; color: white;" href="{% url 'ProjectHomePage' %}">EMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active"  aria-current="page" style="font-weight: bold; color: white;" href="{% url 'EventManagerHomePage' %}">Home </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;"  href="#">Link</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;"  href="{% url 'EventManager_module:Event Post' %}">Event Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;"  href="{% url 'EventManager_module:view_event_details' %}">View Events </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;"  href="{% url 'EventManager_module:event_application_list' %}">View Event Applications </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="font-weight: bold; color: black;" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" style="font-weight: bold; color: black;"  href="#">Action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" style="font-weight: bold; color: black;" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" style="font-weight: bold; color: black;" href="#">Something else here</a></li>
          </ul>
        </li>
      <!-- <li class="nav-item">
          <a class="nav-link disabled"  style="font-weight: bold; color: white;" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>-->
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" style="font-weight: bold; color:white;"  type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" style="font-weight: bold;background-color:#1C2833" type="submit">Search</button>
      </form>
     <!--<ul class = "navbar-nav ms auto">
   <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;" href="{% url 'EventManagerHomePage' %}">Event Manager</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;" href="{% url 'EventParticipantHomePage' %}">Event Participant</a>
        </li>
      </ul>-->
      <ul class = "navbar-nav ms-auto">
        <li>
          {% if user.is_authenticated %}
          <li class = "nav-item">
        <span class = "nav-link" style = "font-weight:bold ; color:white">Welcome,{{user.username}}</span>
        </li>
        <li>
         <div class="profile-dropdown">
                <img id="current-profile-picture" src="https://media.istockphoto.com/id/1300845620/vector/user-icon-flat-isolated-on-white-background-user-symbol-vector-illustration.jpg?s=612x612&w=0&k=20&c=yBeyba0hUkh14_jgv1OKqIH0CCSWU_4ckRkAoy2p73o=" alt="Profile Picture" class="profile-image">
                <div class="dropdown-content">
                     <a href="{% url 'account_details' %}"><i class="fa fa-user"></i> Account</a>
                        <a href="{% url 'user_profile' %}"><i class="fa fa-user-circle-o"></i> Profile</a>
                        <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                </div>
            </div>
        </li>
        <li class = "nav-item">
           <a class="nav-link" style = "font-weight:bold ; color:white" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" style = "font-weight:bold ; color:white" href="{% url 'signup' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style = "font-weight:bold ; color:white" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

{% block body %}

{% endblock %}
<footer id = "sticky-footer" class = "flex-shrink-0 py-2">
  <div class = "container text-center">
    <small> Copyright EMS - KL University. All Rights Reserved by <b>SAKETH KUNUKU</b></small>
  </div>
</footer>
<style>
  #sticky-footer{
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background-color:black;
  color: white;
  padding: 10px;
  font-weight: bold;
  }
</style>
<script>
        // Load user profile data from localStorage if available
        window.onload = function() {
            var loggedInUser = "{{ user.username }}"; // Get the currently logged-in username from the template
            if (loggedInUser) {
                var storedProfile = localStorage.getItem(loggedInUser);
                if (storedProfile) {
                    var userProfile = JSON.parse(storedProfile);
                    document.getElementById('current-profile-picture').src = userProfile.profilePicture;
                }
            }
        };
    </script>
</body>
</html>

templates/Navbar/EventParticipantNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<style>
    /* Dropdown Styles */
        .profile-dropdown {
            position: relative;
            display: inline-block;
        }

        .profile-image {
            width: 40px; /* Adjust as needed */
            height: 40px; /* Adjust as needed */
            border-radius: 50%; /* To make it circular */
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 120px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
            top: 100%; /* Position the dropdown below the profile image */
            right: 0; /* Align the dropdown to the right edge of the profile image */
            animation: fadeIn 0.5s ease;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .profile-dropdown:hover .dropdown-content {
            display: block;
         }
    /* footer section start */
</style>
<nav class="navbar navbar-expand-lg " style ="background-color:black">
  <div class="container-fluid">
    <a class="navbar-brand" style="font-weight: bold; color: white;"  href="{% url 'ProjectHomePage' %}">EMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active"  aria-current="page" style="font-weight: bold; color: white;"  href="{% url 'EventParticipantHomePage' %}">Home </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;" href="{% url 'EventParticipant_module:add_eventparticipant_profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;"  href="{% url 'EventParticipant_module:event_details_list' %}">View Events</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="font-weight: bold; color: blank;" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" style="font-weight: bold; color: black;" href="#">Action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" style="font-weight: bold; color: black;"  href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" style="font-weight: bold; color: black;"  href="#">Something else here</a></li>
          </ul>
        </li>
        <!--<li class="nav-item">
          <a class="nav-link disabled" style="font-weight: bold; color: white;" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>-->
      </ul>
      <form class="d-flex">
    <input class="form-control me-2" type="search" style="font-weight: bold; color: white;" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" style="font-weight: bold; background-color: #1C2833;" type="submit">Search</button>
</form>

     <!--<ul class = "navbar-nav ms auto">
   <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;" href="{% url 'EventManagerHomePage' %}">Event Manager</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="font-weight: bold; color: white;" href="{% url 'EventParticipantHomePage' %}">Event Participant</a>
        </li>
      </ul>-->
      <ul class = "navbar-nav ms-auto">
        <li>
          {% if user.is_authenticated %}
          <li class = "nav-item">
        <span class = "nav-link" style = "font-weight:bold ; color:white">Welcome,{{user.username}}</span>
        </li>
         <div class="profile-dropdown">

                <img id="current-profile-picture" src="https://media.istockphoto.com/id/1300845620/vector/user-icon-flat-isolated-on-white-background-user-symbol-vector-illustration.jpg?s=612x612&w=0&k=20&c=yBeyba0hUkh14_jgv1OKqIH0CCSWU_4ckRkAoy2p73o=" alt="Profile Picture" class="profile-image">
                <div class="dropdown-content">
                     <a href="{% url 'account_details' %}"><i class="fa fa-user"></i> Account</a>
                        <a href="{% url 'user_profile' %}"><i class="fa fa-user-circle-o"></i> Profile</a>
                        <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                </div>
            </div>
        <li class = "nav-item">
           <a class="nav-link" style = "font-weight:bold ; color:white" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" style = "font-weight:bold ; color:white" href="{% url 'signup' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style = "font-weight:bold ; color:white" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

{% block body %}

{% endblock %}
<footer id = "sticky-footer" class = "flex-shrink-0 py-2">
  <div class = "container text-center">
    <small> Copyright OJP - KL University. All Rights Reserved by <b>SAKETH KUNUKU</b></small>
  </div>
</footer>
<style>
  #sticky-footer{
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background-color:black;
  color: white;
  padding: 10px;
  font-weight: bold;
  }


</style>
<script>
        // Load user profile data from localStorage if available
        window.onload = function() {
            var loggedInUser = "{{ user.username }}"; // Get the currently logged-in username from the template
            if (loggedInUser) {
                var storedProfile = localStorage.getItem(loggedInUser);
                if (storedProfile) {
                    var userProfile = JSON.parse(storedProfile);
                    document.getElementById('current-profile-picture').src = userProfile.profilePicture;
                }
            }
        };
    </script>
</body>
</html>